class BootStrap {
def commandsService
    def init = { servletContext ->

        commandsService.init()

//        if (!ProcessConstant.findByIndicator("IM1"))
//            new ProcessConstant(indicator: "IM1", name: "2 SF blanks(CR39)", value: 1.160E-01, unit: "kg", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM2"))
//            new ProcessConstant(indicator: "IM2", name: "Blue protection tape", value: 2.700E-02, unit: "kg", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM3"))
//            new ProcessConstant(indicator: "IM3", name: "Polishing liquid", value: null, unit: "m3", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM4"))
//            new ProcessConstant(indicator: "IM4", name: "Cleaning detergents", value: 1.100E-04, unit: "m3", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM5"))
//            new ProcessConstant(indicator: "IM5", name: "Water based colors", value: 2.000E-03, unit: "m3", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM6"))
//            new ProcessConstant(indicator: "IM6", name: "Hard coat liquid", value: 2.000E-03, unit: "kg", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM7"))
//            new ProcessConstant(indicator: "IM7", name: "Coating materials", value: 5.000E-05, unit: "kg", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM8"))
//            new ProcessConstant(indicator: "IM8", name: "Virgin Polyamide-12 (PA2200) powder", value: 7.670E-02, unit: "kg", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM9"))
//            new ProcessConstant(indicator: "IM9", name: "Polishing media", value: 3.330E-02, unit: "kg", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM10"))
//            new ProcessConstant(indicator: "IM10", name: "Dye", value: 6.000E-04, unit: "l", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM11"))
//            new ProcessConstant(indicator: "IM11", name: "Spray paint", value: 8.000E-04, unit: "kg", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM12"))
//            new ProcessConstant(indicator: "IM12", name: "Solvent", value: 1.700E-03, unit: "kg", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM13"))
//            new ProcessConstant(indicator: "IM13", name: "Lacquer", value: 8.000E-04, unit: "kg", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM14"))
//            new ProcessConstant(indicator: "IM14", name: "Ti powder", value: 2.000E-02, unit: "kg", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM15"))
//            new ProcessConstant(indicator: "IM15", name: "Argon", value: 5.000E-02, unit: "kg", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM16"))
//            new ProcessConstant(indicator: "IM16", name: "Grinding compound", value: 7.500E-01, unit: "kg", type: "input material").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("IM17"))
//            new ProcessConstant(indicator: "IM17", name: "Polishing compound", value: 3.500E-01, unit: "kg", type: "input material").save(failonerror: true, flush: true)
//
//// Energy
//
//        if (!ProcessConstant.findByIndicator("E1"))
//            new ProcessConstant(indicator: "E1", name: "Electricity Lenses", value: 1.638E+00, unit: "kWh", type: "energy").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("E2"))
//            new ProcessConstant(indicator: "E2", name: "Electricity PA frontal", value: 4.300E-01, unit: "kWh", type: "energy").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("E3"))
//            new ProcessConstant(indicator: "E3", name: "Electricity PA temples", value: 4.300E-01, unit: "kWh", type: "energy").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("E4"))
//            new ProcessConstant(indicator: "E4", name: "Electricity Ti Frontal without finish", value: 3.200E+00, unit: "kWh", type: "energy").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("E5"))
//            new ProcessConstant(indicator: "E5", name: "Electricity Ti Frontal with finish", value: 3.300E+00, unit: "kWh", type: "energy").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("E6"))
//            new ProcessConstant(indicator: "E6", name: "Electricity Assembly", value: null, unit: "kWh", type: "energy").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("CA1"))
//            new ProcessConstant(indicator: "CA1", name: "Compressed air Lenses", value: null, unit: "m3", type: "energy").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("CA2"))
//            new ProcessConstant(indicator: "CA2", name: "Compressed air PA frontal", value: 2.670E+00, unit: "m3", type: "energy").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("CA3"))
//            new ProcessConstant(indicator: "CA3", name: "Compressed air PA temples", value: 2.670E+00, unit: "m3", type: "energy").save(failonerror: true, flush: true)
//
//// Water
//
//        if (!ProcessConstant.findByIndicator("W1"))
//            new ProcessConstant(indicator: "W1", name: "Tap water lenses", value: 8.000E-03, unit: "m3", type: "water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("W2"))
//            new ProcessConstant(indicator: "W2", name: "Household grade PA frontal", value: 1.670E-03, unit: "m3", type: "water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("W3"))
//            new ProcessConstant(indicator: "W3", name: "Tap water PA frontal", value: 6.670E-06, unit: "m3", type: "water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("W4"))
//            new ProcessConstant(indicator: "W4", name: "Household grade PA temples", value: 1.670E-03, unit: "m3", type: "water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("W5"))
//            new ProcessConstant(indicator: "W5", name: "Tap water PA temples", value: 6.670E-06, unit: "m3", type: "water").save(failonerror: true, flush: true)
//
////Waste water
//
//        if (!ProcessConstant.findByIndicator("WW1"))
//            new ProcessConstant(indicator: "WW1", name: "Waste polishing liquid lenses", value: 4.020E-03, unit: "m3", type: "waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("WW2"))
//            new ProcessConstant(indicator: "WW2", name: "Waste detergents lenses", value: 1.101E-01, unit: "m3", type: "waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("WW3"))
//            new ProcessConstant(indicator: "WW3", name: "Waste water lenses", value: 1.000E-03, unit: "m3", type: "waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("WW4"))
//            new ProcessConstant(indicator: "WW4", name: "Waste colors lenses", value: 2.000E-03, unit: "m3", type: "waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("WW5"))
//            new ProcessConstant(indicator: "WW5", name: "Waste hard coat liquid lenses", value: 2.000E-03, unit: "m3", type: "waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("WW6"))
//            new ProcessConstant(indicator: "WW6", name: "Household grade PA frontal", value: 1.670E-03, unit: "m3", type: "waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("WW7"))
//            new ProcessConstant(indicator: "WW7", name: "Waste paint PA frontal", value: 4.200E-07, unit: "m3", type: "waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("WW8"))
//            new ProcessConstant(indicator: "WW8", name: "Waste solvent PA frontal", value: 4.200E-07, unit: "m3", type: "waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("WW9"))
//            new ProcessConstant(indicator: "WW9", name: "Waste lacquer PA frontal", value: 4.200E-07, unit: "m3", type: "waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("WW10"))
//            new ProcessConstant(indicator: "WW10", name: "Household grade PA temples", value: 1.670E-03, unit: "m3", type: "waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("WW11"))
//            new ProcessConstant(indicator: "WW11", name: "Waste paint PA temples", value: 4.200E-07, unit: "m3", type: "waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("WW12"))
//            new ProcessConstant(indicator: "WW12", name: "Waste solvent PA temples", value: 4.200E-07, unit: "m3", type: "waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("WW13"))
//            new ProcessConstant(indicator: "WW13", name: "Waste Lacquer PA temples", value: 4.200E-07, unit: "m3", type: "waste water").save(failonerror: true, flush: true)
//
//// Transport waste water
//
//        if (!ProcessConstant.findByIndicator("TWW1"))
//            new ProcessConstant(indicator: "TWW1", name: "Transport Waste polishing liquid lenses", value: 8.000E-05, unit: "kgkm", type: "transport waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TWW2"))
//            new ProcessConstant(indicator: "TWW2", name: "Transport Waste detergents lenses", value: 0.000E+00, unit: "kgkm", type: "transport waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TWW3"))
//            new ProcessConstant(indicator: "TWW3", name: "Transport Waste water lenses", value: 0.000E+00, unit: "kgkm", type: "transport waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TWW4"))
//            new ProcessConstant(indicator: "TWW4", name: "Transport Waste colors lenses", value: 0.000E+00, unit: "kgkm", type: "transport waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TWW5"))
//            new ProcessConstant(indicator: "TWW5", name: "Transport Waste hard coat liquid lenses", value: 2.000E-03, unit: "kgkm", type: "transport waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TWW6"))
//            new ProcessConstant(indicator: "TWW6", name: "Transport Household grade PA frontal", value: 0.000E+00, unit: "kgkm", type: "transport waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TWW7"))
//            new ProcessConstant(indicator: "TWW7", name: "Transport Waste paint PA frontal", value: 2.900E-03, unit: "kgkm", type: "transport waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TWW8"))
//            new ProcessConstant(indicator: "TWW8", name: "Transport Waste solvent PA frontal", value: 2.900E-03, unit: "kgkm", type: "transport waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TWW9"))
//            new ProcessConstant(indicator: "TWW9", name: "Transport Waste lacquer PA frontal", value: 2.900E-03, unit: "kgkm", type: "transport waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TWW10"))
//            new ProcessConstant(indicator: "TWW10", name: "Transport Household grade PA temples", value: 0.000E+00, unit: "kgkm", type: "transport waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TWW11"))
//            new ProcessConstant(indicator: "TWW11", name: "Transport Waste paint PA temples", value: 2.900E-03, unit: "kgkm", type: "transport waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TWW12"))
//            new ProcessConstant(indicator: "TWW12", name: "Transport Waste solvent PA temples", value: 2.900E-03, unit: "kgkm", type: "transport waste water").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TWW13"))
//            new ProcessConstant(indicator: "TWW13", name: "Transport Waste Lacquer PA temples", value: 2.900E-04, unit: "kgkm", type: "transport waste water").save(failonerror: true, flush: true)
//
//// Solid waste
//
//        if (!ProcessConstant.findByIndicator("SW1"))
//            new ProcessConstant(indicator: "SW1", name: "Paper box (lenses)", value: 2.000E-02, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW2"))
//            new ProcessConstant(indicator: "SW2", name: "Plastic case (lenses)", value: 6.000E-03, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW3"))
//            new ProcessConstant(indicator: "SW3", name: "Blue tape waste (lenses)", value: 3.000E-02, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW4"))
//            new ProcessConstant(indicator: "SW4", name: "Lens material waste (lenses)", value: 1.000E-01, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW5"))
//            new ProcessConstant(indicator: "SW5", name: "Virgin powder Packaging-LDPE (PA frontal)", value: 3830E-06, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW6"))
//            new ProcessConstant(indicator: "SW6", name: "Rejected parts (PA frontal)", value: 4.400E-02, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW7"))
//            new ProcessConstant(indicator: "SW7", name: "Agglomerated powder (PA frontal)", value: 1.330E-02, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW8"))
//            new ProcessConstant(indicator: "SW8", name: "Polishing media packaging LDPE (PA frontal)", value: 1.330E-05, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW9"))
//            new ProcessConstant(indicator: "SW9", name: "Dye packaging steel can recycling (PA frontal)", value: 4.330E-04, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW10"))
//            new ProcessConstant(indicator: "SW10", name: "Paint packaging (steel can)(PA frontal)", value: 4.330E-04, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW11"))
//            new ProcessConstant(indicator: "SW11", name: "Solvent packaging (steel can)(PA frontal)", value: 8.670E-04, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW12"))
//            new ProcessConstant(indicator: "SW12", name: "Dust filter (filter media)(PA frontal)", value: 2.000E+00, unit: "units", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW13"))
//            new ProcessConstant(indicator: "SW13", name: "Lacquer packaging (steel case)(PA frontal)", value: 1.670E-05, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW14"))
//            new ProcessConstant(indicator: "SW14", name: "Virgin powder Packaging-LDPE (PA temple)", value: 3.830E-06, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW15"))
//            new ProcessConstant(indicator: "SW15", name: "Regected parts (PA temple)", value: 4.400E-02, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW16"))
//            new ProcessConstant(indicator: "SW16", name: "Agglomerated powder (PA temple)", value: 1.330E-02, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW17"))
//            new ProcessConstant(indicator: "SW17", name: "Polishing media packaging LDPE (PA temple)", value: 1.330E-05, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW18"))
//            new ProcessConstant(indicator: "SW18", name: "Dye packaging steel can recycling (PA temple)", value: 4.330E-04, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW19"))
//            new ProcessConstant(indicator: "SW19", name: "Paint packaging (steel can)(PA temple)", value: 4.330E-04, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW20"))
//            new ProcessConstant(indicator: "SW20", name: "Solvent packaging (steel can)(PA temple)", value: 8.670E-04, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW21"))
//            new ProcessConstant(indicator: "SW21", name: "Dust filter (filter media)(PA temple)", value: 2.000E+00, unit: "units", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW22"))
//            new ProcessConstant(indicator: "SW22", name: "Lacquer packaging (steel case)(PA temple)", value: 1.670E-05, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW23"))
//            new ProcessConstant(indicator: "SW23", name: "Packaging Ti powder (HDPE)(Ti frontal)", value: 1.328E-01, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW24"))
//            new ProcessConstant(indicator: "SW24", name: "Argon (Ti frontal)", value: 2848E+00, unit: "l", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW25"))
//            new ProcessConstant(indicator: "SW25", name: "Titanium supports or rejected parts (Ti frontal)", value: 2.900E-04, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW26"))
//            new ProcessConstant(indicator: "SW26", name: "Dried powder (landfill)", value: 1.125E+00, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW27"))
//            new ProcessConstant(indicator: "SW27", name: "Jerrycan (HDPE)", value: 1750E-01, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("SW28"))
//            new ProcessConstant(indicator: "SW28", name: "Bag (PP)", value: 0.00125, unit: "kg", type: "solid waste").save(failonerror: true, flush: true)
//
////Transport solid waste
//
//        if (!ProcessConstant.findByIndicator("TSW1"))
//            new ProcessConstant(indicator: "TSW1", name: "Transport Paper box (lenses)", value: 2.000E-02, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW2"))
//            new ProcessConstant(indicator: "TSW2", name: "Transport Plastic case (lenses)", value: 6.000E-03, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW3"))
//            new ProcessConstant(indicator: "TSW3", name: "Transport Blue tape waste (lenses)", value: 1.000E-02, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW4"))
//            new ProcessConstant(indicator: "TSW4", name: "Transport Lens material waste (lenses)", value: 1.000E-01, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW5"))
//            new ProcessConstant(indicator: "TSW5", name: "Transport Virgin powder Packaging-LDPE (PA frontal)", value: null, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW6"))
//            new ProcessConstant(indicator: "TSW6", name: "Transport Rejected parts (PA frontal)", value: 5.000E-04, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW7"))
//            new ProcessConstant(indicator: "TSW7", name: "Transport Agglomerated powder (PA frontal)", value: 9.300E-02, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW8"))
//            new ProcessConstant(indicator: "TSW8", name: "Transport Polishing media packaging LDPE (PA frontal)", value: null, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW9"))
//            new ProcessConstant(indicator: "TSW9", name: "Transport Dye packaging steel can recycling (PA frontal)", value: null, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW10"))
//            new ProcessConstant(indicator: "TSW10", name: "Transport Paint packaging (steel can)(PA frontal)", value: 3.030E-03, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW11"))
//            new ProcessConstant(indicator: "TSW11", name: "Transport Solvent packaging (steel can)(PA frontal)", value: 6.070E-03, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW12"))
//            new ProcessConstant(indicator: "TSW12", name: "Transport Dust filter (filter media)(PA frontal)", value: null, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW13"))
//            new ProcessConstant(indicator: "TSW13", name: "Transport Lacquer packaging (steel case)(PA frontal)", value: 3.030E-03, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW14"))
//            new ProcessConstant(indicator: "TSW14", name: "Transport Virgin powder Packaging-LDPE (PA temple)", value: null, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW15"))
//            new ProcessConstant(indicator: "TSW15", name: "Transport Regected parts (PA temple)", value: 5.000E-04, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW16"))
//            new ProcessConstant(indicator: "TSW16", name: "Transport Agglomerated powder (PA temple)", value: 9.300E-02, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW17"))
//            new ProcessConstant(indicator: "TSW17", name: "Transport Polishing media packaging LDPE (PA temple)", value: null, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW18"))
//            new ProcessConstant(indicator: "TSW18", name: "Transport Dye packaging steel can recycling (PA temple)", value: null, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW19"))
//            new ProcessConstant(indicator: "TSW19", name: "Transport Paint packaging (steel can)(PA temple)", value: 3.030E-03, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW20"))
//            new ProcessConstant(indicator: "TSW20", name: "Transport Solvent packaging (steel can)(PA temple)", value: 6.070E-03, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW21"))
//            new ProcessConstant(indicator: "TSW21", name: "Transport Dust filter (filter media)(PA temple)", value: null, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW22"))
//            new ProcessConstant(indicator: "TSW22", name: "Transport Lacquer packaging (steel case)(PA temple)", value: 3.030E-03, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW23"))
//            new ProcessConstant(indicator: "TSW23", name: "Transport Packaging Ti powder (HDPE)(Ti frontal)", value: 2.665E+00, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW24"))
//            new ProcessConstant(indicator: "TSW24", name: "Transport Argon (Ti frontal)", value: null, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW25"))
//            new ProcessConstant(indicator: "TSW25", name: "Transport Titanium supports or rejected parts (Ti frontal)", value: 2.020E-01, unit: "kgkm", type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW26"))
//            new ProcessConstant(indicator: "TSW26", name: "Transport Dried powder", value: null, unit: null, type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW27"))
//            new ProcessConstant(indicator: "TSW27", name: "Transport Jerrycan", value: null, unit: null, type: "transport solid waste").save(failonerror: true, flush: true)
//        if (!ProcessConstant.findByIndicator("TSW28"))
//            new ProcessConstant(indicator: "TSW28", name: "Transport Bag", value: null, unit: null, type: "transport solid waste").save(failonerror: true, flush: true)
//
///* NO LONGER A PROCESS CONSTANT
//
//// Transport input material
//
//if (!ProcessConstant.findByIndicator("TIM1"))
//    new ProcessConstant(indicator:"TIM1",name:"Transport 2 SF blanks(CR39)", value: , unit: "kgkm", type: "transport input material").save(failonerror: true, flush:true)
//if (!ProcessConstant.findByIndicator("TIM2"))
//    new ProcessConstant(indicator:"TIM2",name:"Transport Blue protection tape", value: , unit: "kgkm", type: "transport input material").save(failonerror: true, flush:true)
//if (!ProcessConstant.findByIndicator("TIM3"))
//    new ProcessConstant(indicator:"TIM3",name:"Transport Polishing liquid", value: , unit: "kgkm", type: "transport input material").save(failonerror: true, flush:true)
//if (!ProcessConstant.findByIndicator("TIM4"))
//    new ProcessConstant(indicator:"TIM4",name:"Transport Cleaning detergents", value: , unit: "kgkm", type: "transport input material").save(failonerror: true, flush:true)
//if (!ProcessConstant.findByIndicator("TIM5"))
//   new ProcessConstant(indicator:"TIM5", name:"Transport Water based colors", value: , unit: "kgkm", type: "transport nput material").save(failonerror: true, flush: true)
//if (!ProcessConstant.findByIndicator("TIM6"))
//   new ProcessConstant(indicator:"TIM6", name:"Transport Hard coat liquid", value: , unit: "kgkm", type: "transport input material").save(failonerror: true, flush: true)
//if (!ProcessConstant.findByIndicator("TIM7"))
//   new ProcessConstant(indicator:"TIM7", name:"Transport Coating materials", value: , unit: "kgkm", type: "transport input material").save(failonerror: true, flush: true)
//if (!ProcessConstant.findByIndicator("TIM8"))
//   new ProcessConstant(indicator:"TIM8", name:"Transport Virgin Polyamide-12 (PA2200) powder", value: 9.583E+01, unit: "kgkm", type: "transport input material").save(failonerror: true, flush: true)
//if (!ProcessConstant.findByIndicator("TIM9"))
//   new ProcessConstant(indicator:"TIM9", name:"Transport Polishing media", value: 1.330E+00, unit: "kgkm", type: "transport input material").save(failonerror: true, flush: true)
//if (!ProcessConstant.findByIndicator("TIM10"))
//   new ProcessConstant(indicator:"TIM10", name:"Transport Dye", value: , unit: "kgkm", type: "transport input material").save(failonerror: true, flush: true)
//if (!ProcessConstant.findByIndicator("TIM11")
//   new ProcessConstant(indicator:"TIM11", name:"Transport Spray paint", value: 1.000E-02, unit: "kgkm", type: "transport input material").save(failonerror: true, flush: true)
//if (!ProcessConstant.findByIndicator("TIM12"))
//   new ProcessConstant(indicator:"TIM12", name:"Transport Solvent", value: 1.000E-02, unit: "kgkm", type: "transport input material").save(failonerror: true, flush: true)
//if (!ProcessConstant.findByIndicator("TIM13"))
//   new ProcessConstant(indicator:"TIM13", name:"Transport Lacquer", value: 1.000E-02, unit: "kgkm", type: "transport input material").save(failonerror: true, flush: true)
//if (!ProcessConstant.findByIndicator("TIM14"))
//   new ProcessConstant(indicator:"TIM14", name:"Transport Ti powder", value: 1.350E+03, unit: "kgkm", type: "transport input material").save(failonerror: true, flush: true)
//
//*/
//
//// Template
//
////        if (!ProcessConstant.findByIndicator(""))
////            new ProcessConstant(indicator:"", name:"", value: E, unit: "", type: "").save(failonerror: true, flush: true)
////
////
//
////        if(ProcessConstant.sizeByType("input material") !== 14) {
////            if (!ProcessConstant.findByIndicator("IM1"))
////                new ProcessConstant(indicator:"IM1",name:"2 SF blanks(CR39)", value: 1.160E-01, unit: "kg", type: "input material").save(failonerror: true, flush:true)
////            if (!ProcessConstant.findByIndicator("IM2"))
////                new ProcessConstant(indicator:"IM2",name:"Blue protection tape", value: 2.700E-02, unit: "kg", type: "input material").save(failonerror: true, flush:true)
////            if (!ProcessConstant.findByIndicator("IM3"))
////                new ProcessConstant(indicator:"IM3",name:"Polishing liquid", value: 4.000E-05, unit: "m3", type: "input material").save(failonerror: true, flush:true)
////            if (!ProcessConstant.findByIndicator("IM4"))
////                new ProcessConstant(indicator:"IM4",name:"Cleaning detergents", value: 1.100E-04, unit: "m3", type: "input material").save(failonerror: true, flush:true)
////            if (!ProcessConstant.findByIndicator("IM1"))
////                new ProcessConstant(indicator:"IM1",name:"2 SF blanks(CR39)")
////            if (!ProcessConstant.findByIndicator("IM1"))
////                new ProcessConstant(indicator:"IM1",name:"2 SF blanks(CR39)")
////            if (!ProcessConstant.findByIndicator("IM1"))
////                new ProcessConstant(indicator:"IM1",name:"2 SF blanks(CR39)")
////            if (!ProcessConstant.findByIndicator("IM1"))
////                new ProcessConstant(indicator:"IM1",name:"2 SF blanks(CR39)")
////            if (!ProcessConstant.findByIndicator("IM1"))
////                new ProcessConstant(indicator:"IM1",name:"2 SF blanks(CR39)")
////            if (!ProcessConstant.findByIndicator("IM1"))
////                new ProcessConstant(indicator:"IM1",name:"2 SF blanks(CR39)")
////            if (!ProcessConstant.findByIndicator("IM1"))
////                new ProcessConstant(indicator:"IM1",name:"2 SF blanks(CR39)")
////            if (!ProcessConstant.findByIndicator("IM1"))
////                new ProcessConstant(indicator:"IM1",name:"2 SF blanks(CR39)")
////            if (!ProcessConstant.findByIndicator("IM1"))
////                new ProcessConstant(indicator:"IM1",name:"2 SF blanks(CR39)")
////            if (!ProcessConstant.findByIndicator("IM1"))
////                new ProcessConstant(indicator:"IM1",name:"2 SF blanks(CR39)")
////
        
    }
    def destroy = {
    }
}
